// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgmttgvtkeyclurnkjro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnbXR0Z3Z0a2V5Y2x1cm5ranJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTE4MDcsImV4cCI6MjA1Nzg4NzgwN30.5WufxmiNTmZ3dO2Y0kE-YSqBgvDWh9K-DqUaGNv09Zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);